

/gate/source/addSource                          phsp_source phaseSpace
/gate/source/phsp_source/addPhaseSpaceFile      {SOURCE_PHSP_PT}
/gate/source/phsp_source/setParticleType        gamma
/gate/source/phsp_source/setPytorchParams       {SOURCE_PHSP_JSON}
/gate/source/phsp_source/setPytorchBatchSize    1000000
/gate/source/phsp_source/attachTo               target_layer
/gate/source/phsp_source/useRandomSymmetry      false
/gate/source/phsp_source/ignoreWeight           true





/control/multiply N_START {JOB_ID} {N}
/gate/source/phsp_source/setStartingParticleId  {N_START}


